"use client";

import { useState, useEffect } from "react";
import Link from "next/link";

// Demo skits data
const DEMO_SKITS = [
  { id: "1", title: "When the WiFi drops during a Zoom meeting", category: "comedy", creator: "AI Comedy Lab", duration: 28, views: 12400, likes: 890, isPremium: false, thumb: "🤣" },
  { id: "2", title: "POV: You're the last slice of pizza", category: "comedy", creator: "SkitBot", duration: 22, views: 28300, likes: 2100, isPremium: false, thumb: "🍕" },
  { id: "3", title: "How cats see vacuum cleaners", category: "animals", creator: "PetAI Studios", duration: 35, views: 45100, likes: 3200, isPremium: false, thumb: "🐱" },
  { id: "4", title: "The Karen vs the self-checkout machine", category: "comedy", creator: "AI Comedy Lab", duration: 40, views: 67800, likes: 5400, isPremium: true, thumb: "😤" },
  { id: "5", title: "When autocorrect ruins your job interview text", category: "relatable", creator: "SkitBot", duration: 25, views: 31200, likes: 2800, isPremium: true, thumb: "📱" },
  { id: "6", title: "Dog realizes it's bath day", category: "animals", creator: "PetAI Studios", duration: 30, views: 52400, likes: 4100, isPremium: false, thumb: "🐕" },
  { id: "7", title: "Boss catches you dancing at your desk", category: "relatable", creator: "OfficeAI", duration: 33, views: 19700, likes: 1500, isPremium: true, thumb: "💃" },
  { id: "8", title: "When the GPS says 'you have arrived' but you haven't", category: "comedy", creator: "AI Comedy Lab", duration: 27, views: 38900, likes: 3100, isPremium: false, thumb: "🗺️" },
  { id: "9", title: "Cat judges your life choices at 3am", category: "animals", creator: "PetAI Studios", duration: 31, views: 71200, likes: 6200, isPremium: true, thumb: "🐈‍⬛" },
  { id: "10", title: "The group chat when someone says 'who's paying?'", category: "relatable", creator: "SkitBot", duration: 24, views: 44300, likes: 3700, isPremium: false, thumb: "💰" },
];

const CATEGORIES = [
  { slug: "all", name: "🔥 All", },
  { slug: "comedy", name: "😂 Comedy" },
  { slug: "relatable", name: "🤷 Relatable" },
  { slug: "animals", name: "🐾 Animals" },
  { slug: "drama", name: "🎭 Drama" },
  { slug: "horror", name: "👻 Horror" },
];

export default function Home() {
  const [selectedCategory, setSelectedCategory] = useState("all");
  const [playingId, setPlayingId] = useState<string | null>(null);

  const filtered = selectedCategory === "all" ? DEMO_SKITS : DEMO_SKITS.filter((s) => s.category === selectedCategory);

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white">
      {/* Nav */}
      <nav className="sticky top-0 z-50 bg-[#0a0a0a]/90 backdrop-blur-xl border-b border-white/5">
        <div className="max-w-6xl mx-auto flex items-center justify-between px-6 py-4">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl flex items-center justify-center text-lg font-black" style={{ background: "linear-gradient(135deg, #8b5cf6, #ec4899)" }}>S</div>
            <span className="font-extrabold text-xl gradient-text">ShortReels</span>
          </div>
          <div className="hidden md:flex items-center gap-6">
            <a href="#feed" className="text-sm font-medium text-gray-400 hover:text-white transition">Browse</a>
            <a href="#pricing" className="text-sm font-medium text-gray-400 hover:text-white transition">Pricing</a>
          </div>
          <div className="flex items-center gap-3">
            <Link href="/login" className="text-sm font-semibold text-gray-400 hover:text-white transition px-4 py-2">Log in</Link>
            <Link href="/register" className="btn-brand !py-2.5 !px-5 !text-sm !rounded-full">Get Started</Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="py-20 px-6 text-center relative overflow-hidden">
        <div className="absolute inset-0" style={{ background: "radial-gradient(ellipse at 50% 0%, rgba(139,92,246,0.15) 0%, transparent 60%)" }} />
        <div className="relative z-10 max-w-3xl mx-auto">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-white/5 border border-white/10 text-sm text-gray-400 mb-6">
            <span className="w-2 h-2 bg-pink-500 rounded-full animate-pulse" /> New AI skits daily
          </div>
          <h1 className="text-4xl md:text-6xl font-black leading-tight mb-6">
            AI Skits You <span className="gradient-text">Can't Stop</span> Watching
          </h1>
          <p className="text-lg text-gray-400 mb-8 max-w-xl mx-auto">
            Hilarious, mind-bending, and totally addictive short reels — all generated by AI. New skits every day.
          </p>
          <div className="flex items-center justify-center gap-4">
            <Link href="/register" className="btn-brand !py-3.5 !px-8 !rounded-full !text-base" style={{ boxShadow: "0 4px 20px rgba(139,92,246,0.4)" }}>
              Start Watching Free
            </Link>
            <a href="#feed" className="text-base font-semibold text-gray-400 hover:text-white transition">Browse Skits ↓</a>
          </div>
          <div className="flex items-center justify-center gap-8 mt-10 text-sm text-gray-500">
            <span>🎬 1000+ skits</span>
            <span>🤖 AI-generated</span>
            <span>📱 Mobile-friendly</span>
          </div>
        </div>
      </section>

      {/* Feed */}
      <section id="feed" className="px-6 pb-20">
        <div className="max-w-6xl mx-auto">
          {/* Categories */}
          <div className="flex items-center gap-2 mb-8 overflow-x-auto pb-2">
            {CATEGORIES.map((cat) => (
              <button key={cat.slug} onClick={() => setSelectedCategory(cat.slug)} className={`px-4 py-2 rounded-full text-sm font-semibold whitespace-nowrap transition ${selectedCategory === cat.slug ? "bg-white text-black" : "bg-white/5 text-gray-400 hover:bg-white/10"}`}>
                {cat.name}
              </button>
            ))}
          </div>

          {/* Skit Grid — TikTok-style vertical cards */}
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
            {filtered.map((skit) => (
              <div key={skit.id} className="skit-card group" onClick={() => setPlayingId(playingId === skit.id ? null : skit.id)}>
                <div className="relative rounded-2xl overflow-hidden bg-[#141414] border border-white/5" style={{ aspectRatio: "9/14" }}>
                  {/* Thumbnail */}
                  <div className="absolute inset-0 flex items-center justify-center" style={{ background: `linear-gradient(135deg, rgba(139,92,246,0.15), rgba(236,72,153,0.15))` }}>
                    <span className="text-5xl">{skit.thumb}</span>
                  </div>

                  {/* Play overlay */}
                  <div className="absolute inset-0 flex items-center justify-center bg-black/30 opacity-0 group-hover:opacity-100 transition">
                    <div className="w-12 h-12 rounded-full flex items-center justify-center text-xl" style={{ background: "linear-gradient(135deg, #8b5cf6, #ec4899)" }}>▶</div>
                  </div>

                  {/* Premium badge */}
                  {skit.isPremium && (
                    <div className="absolute top-2 right-2">
                      <span className="tag tag-pink text-[9px]">👑 PRO</span>
                    </div>
                  )}

                  {/* Duration */}
                  <div className="absolute bottom-2 right-2 bg-black/60 px-1.5 py-0.5 rounded text-[10px] font-medium">
                    0:{skit.duration.toString().padStart(2, "0")}
                  </div>

                  {/* Bottom gradient + info */}
                  <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/80 to-transparent p-3 pt-8">
                    <p className="text-xs font-semibold leading-tight line-clamp-2">{skit.title}</p>
                    <p className="text-[10px] text-gray-400 mt-1">{skit.creator}</p>
                  </div>
                </div>

                {/* Stats below card */}
                <div className="flex items-center gap-3 mt-2 px-1">
                  <span className="text-[10px] text-gray-500">❤️ {skit.likes >= 1000 ? `${(skit.likes/1000).toFixed(1)}k` : skit.likes}</span>
                  <span className="text-[10px] text-gray-500">👁️ {skit.views >= 1000 ? `${(skit.views/1000).toFixed(1)}k` : skit.views}</span>
                </div>
              </div>
            ))}
          </div>

          {/* Unlock more CTA */}
          <div className="mt-12 text-center">
            <div className="inline-block card !p-8 text-center max-w-md">
              <span className="text-3xl mb-3 block">👑</span>
              <h3 className="text-xl font-bold mb-2">Unlock Premium Skits</h3>
              <p className="text-sm text-gray-400 mb-4">Get unlimited access to all premium AI skits, early releases, and custom requests.</p>
              <Link href="/register" className="btn-brand !rounded-full !px-8">Upgrade to Pro — $4.99/mo</Link>
            </div>
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-20 px-6 bg-[#0d0d0d]">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-3xl font-black mb-2">Choose Your <span className="gradient-text">Plan</span></h2>
          <p className="text-gray-500 mb-10">Start free. Go Pro when you're hooked.</p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-2xl mx-auto">
            <div className="card text-left">
              <h3 className="text-lg font-bold mb-1">Free</h3>
              <p className="text-gray-500 text-sm mb-4">Taste the AI magic</p>
              <div className="mb-4"><span className="text-4xl font-black gradient-text">$0</span><span className="text-gray-500 text-sm">/forever</span></div>
              <ul className="space-y-2 mb-6">
                {["Watch free skits", "Browse all categories", "Like & share", "5 skits/day limit"].map((f, i) => (
                  <li key={i} className="flex items-center gap-2 text-sm text-gray-400"><span className="text-purple-400">✓</span>{f}</li>
                ))}
              </ul>
              <Link href="/register" className="btn-soft w-full block text-center">Get Started</Link>
            </div>
            <div className="card text-left !border-purple-500/50 relative" style={{ background: "linear-gradient(135deg, rgba(139,92,246,0.05), rgba(236,72,153,0.05))" }}>
              <div className="absolute -top-3 left-1/2 -translate-x-1/2 px-4 py-1 rounded-full text-xs font-bold text-white" style={{ background: "linear-gradient(135deg, #8b5cf6, #ec4899)" }}>Most Popular</div>
              <h3 className="text-lg font-bold mb-1">Pro</h3>
              <p className="text-gray-500 text-sm mb-4">Unlimited AI entertainment</p>
              <div className="mb-4"><span className="text-4xl font-black gradient-text">$4.99</span><span className="text-gray-500 text-sm">/month</span></div>
              <ul className="space-y-2 mb-6">
                {["Unlimited skits", "All premium content", "Early access releases", "Request custom skits", "No ads", "HD quality"].map((f, i) => (
                  <li key={i} className="flex items-center gap-2 text-sm text-gray-400"><span className="text-purple-400">✓</span>{f}</li>
                ))}
              </ul>
              <Link href="/register" className="btn-brand w-full block text-center">Start Pro Trial</Link>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 px-6">
        <div className="max-w-2xl mx-auto text-center rounded-3xl p-12" style={{ background: "linear-gradient(135deg, #8b5cf6, #ec4899)" }}>
          <h2 className="text-3xl font-black text-white mb-2">Ready to laugh?</h2>
          <p className="text-white/70 mb-8">Join 10,000+ people watching AI skits daily.</p>
          <Link href="/register" className="inline-block bg-white text-purple-700 px-8 py-3 rounded-full font-bold text-sm hover:scale-105 transition-transform shadow-lg">Get Started Free</Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 px-6 border-t border-white/5 text-center">
        <div className="flex items-center justify-center gap-2 mb-4">
          <div className="w-7 h-7 rounded-lg flex items-center justify-center text-sm font-black" style={{ background: "linear-gradient(135deg, #8b5cf6, #ec4899)" }}>S</div>
          <span className="font-bold gradient-text">ShortReels</span>
        </div>
        <p className="text-sm text-gray-600">© 2026 ShortReels. All rights reserved.</p>
      </footer>
    </div>
  );
}
